# ============================================
# ArgoCD Helm Values

# helm upgrade argocd argo/argo-cd -n argocd -f argocd-values.yaml
# ============================================

global:
  domain: argocd.local

server:
  extraArgs:
    - --insecure

  service:
    type: ClusterIP
    servicePortHttp: 8080
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https

  ingress:
    enabled: false

  #  enables argocd-server-metrics service (port 8083)
  metrics:
    enabled: true
    service:
      type: ClusterIP
      servicePort: 8083
      portName: http-metrics

#  enables argocd-metrics service (port 8082)
controller:
  metrics:
    enabled: true
    service:
      type: ClusterIP
      servicePort: 8082
      portName: http-metrics


configs:
  params:
    server.insecure: true

  cm:
    # Admin account with apiKey + login
    accounts.admin: apiKey, login

    # Dedicated CI/CD service account
    accounts.cicd: apiKey

  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:cicd, applications, *, */*, allow
      p, role:cicd, clusters, get, *, allow
      p, role:cicd, repositories, get, *, allow
      p, role:cicd, projects, get, *, allow
      g, cicd, role:cicd


# ============================================
# ADD THIS BLOCK — Notifications
# ============================================
notifications:
  enabled: true          # starts the notifications controller pod
  cm:
    create: false       # do not create ConfigMap, we will apply our own with templates and triggers
  secret:
    create: true   
    



repoServer:
  metrics:
    enabled: true
    service:
      servicePort: 8084     # creates argocd-notifications-secret (for tokens/passwords)

