---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    email-password: AgCo7hfqCIso6oiyRsPgP4tyNqzhloy0ldmnAl4gwh/2aYIJWUJxp6RLzPKFhDkecdau7nvJmxcWt4jLSmZRl+N4LPaYaMN2anXmfoed1tzpl3s0IYZ2vx5cp3QcZGHq4gb5OAACfxRexC1sde/WLIrwnKAM2hqwwSugsMSu6TTBNeWCFfivHESZOm4rAdjrAzwkoRnaOMy0X19o+F0MUiFFpkzAT3kO+3yg8rv2a8AeKZ0k1Oc7r8cgF9Q/TgIQmBZIrr7qORg5F1LiD5UpNtvhBKgGC60hcW3lmTYjtgHV9+oU5sO4ahzv+O1keuWQ/oOf7Nq+rDjWs4CFd2aIDAlOzamCoZw3uXpa1bTJt0MXQsLEs5imPb3kMaFUQT9DFA6S/3eWDA2AFx2Ej+AlbRHyo7NUMEsZcKG6nhQRnSDlVna/xrJ5yu7gCS7SSJZ9jjYyMGum6ZVW/awwqNWMkZGg5rqerl+Y3wB/QdFDh5rgcBVy9dZp67UMqZQuDwBCg5QAln87QkVgk2rmdkoaH0hm74lI5V44eYKV0a0GcAsrkv3YWlDpBVd71ObFrpVovXFJTPGpjCK7Zr5OtX31fM3VaUhPPGUKhAUrs5f7ybqe8bvHYEg8cUCsQrLYRYk1k+6Ark0tp1Cqlh3PvTA4qX42XfG9md0B3/LqGZlwctZTQqgM8thlFoTt8VGhsJHUxH8XnMtiuo6TaqV4incCVygi
    email-username: AgAmFy07J4GzbnpzzDk8Qusd0SywXlVkeDroDR+v4h/hCZvVrVLAbeuF4X1ORdL34vWQqcUEgA3OB3pNUFpNUXGDxU5Wg4n6NnqIYd3czi2HUJMlHuwPTG65a37Ll5MQsegFwVGnqYaXEmI2EZyDAoXNb/mL0mhNoxuqc0EUCQADmR2URoVOaHGpQMkHl87+JzWelQRQGDX4O6dgzKPbReU14Z737f8E/POEpNPZN8tw3CLFoaEanVWeNpPWxrEfFItvbRBBrioJS63pPd4ZH3MsuoZ2MLlPBPlB/yzAPiYnvkuGrQfoIoDXPA12OkbcXY0lc+XXONepPP14/g2ZAMrdZl0KhsUKh1uGJ+JjoAsXmenijHsOct79fx0l4JOSsMLfupSBNtRTp9nNi6ANzk4i+ZQ6FBDs1/WJedbMvGiQCOnUcvF1B2yz9vhNJ4u7FaavGxVX4U/KBLNb9nmTu/2HFdKzM8+bbmtZZUU1FNfhGJYOin6qvDbuKDLfzvMUgVDHWCR26eRtwFw3wnWMGk5LgvNuHuL7Jj9zr4VegZxo81BSYUFDrSYCrs4OCMkjA5y3+fK/gm2DmDgPq5WJQPwDRR6cifqBSvT0Bz6I4vO3/woSibaW0RtDuAcReheNdiNRCwkWP6rnJA9KsIdzBMbLRkCQp+G9Pi5trVmJvGwTlKGZPSjvg+sIFv866M6nA2a2pfZL1U3i3e3Ps4RcgxtMQHAzCTG3mEBFGI17
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
