apiVersion: argoproj.io/v1alpha1 # ArgoCD Application resource
kind: Application               # Kind of resource
metadata:                        # Metadata section                         
  name: nginx-frontend          # App name
  namespace: argocd             # Must exist in ArgoCD namespace
  annotations:
    # The email notifier must be configured in argocd-notifications-cm.yaml, The `.email` is the name of the notifier, i.e, `service.email` in the argocd-notifications-cm.yaml.
    # Subscribe to notifications when the app health is degraded.
    notifications.argoproj.io/subscribe.on-health-degraded.email: "jinalpatel11121999@gmail.com"  # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
    # Subscribe to notifications when the app is successfully deployed.
    notifications.argoproj.io/subscribe.on-deployed.email: "jinalpatel11121999@gmail.com" # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
spec:
  project: frontend-team        # Assigns app to the frontend-team Project
  source:
    repoURL: https://github.com/LondheShubham153/argocd-demos.git  # Git repo
    targetRevision: main        # Branch to watch
    path: ui_approach/nginx     # Path in repo with manifests
  destination:
    server: https://kubernetes.default.svc  # Target cluster, run `argocd cluster list` to see
    namespace: frontend          # Namespace inside that cluster
  syncPolicy:                    # Sync policy settings
    automated:                   # Enable automated sync
      prune: true                 # Delete resources removed from Git
      selfHeal: true              # Correct drift if resources change in cluster
    syncOptions:                 # Additional sync options
      - CreateNamespace=true      # Auto-create namespace if it doesn't exist